classdef DeviceRange < robotics.ros.Message
    %DeviceRange MATLAB implementation of pozyx_ros_examples/DeviceRange
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'pozyx_ros_examples/DeviceRange' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '7e348650b1f89edc919c188257fda8b2' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Timestamp
        Distance
        RSS
        Device
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Device', 'Distance', 'RSS', 'Timestamp'} % List of non-constant message properties
        ROSPropertyList = {'device', 'distance', 'RSS', 'timestamp'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = DeviceRange(msg)
            %DeviceRange Construct the message object DeviceRange
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function timestamp = get.Timestamp(obj)
            %get.Timestamp Get the value for property Timestamp
            timestamp = typecast(int32(obj.JavaMessage.getTimestamp), 'uint32');
        end
        
        function set.Timestamp(obj, timestamp)
            %set.Timestamp Set the value for property Timestamp
            validateattributes(timestamp, {'numeric'}, {'nonempty', 'scalar'}, 'DeviceRange', 'Timestamp');
            
            obj.JavaMessage.setTimestamp(timestamp);
        end
        
        function distance = get.Distance(obj)
            %get.Distance Get the value for property Distance
            distance = typecast(int32(obj.JavaMessage.getDistance), 'uint32');
        end
        
        function set.Distance(obj, distance)
            %set.Distance Set the value for property Distance
            validateattributes(distance, {'numeric'}, {'nonempty', 'scalar'}, 'DeviceRange', 'Distance');
            
            obj.JavaMessage.setDistance(distance);
        end
        
        function rss = get.RSS(obj)
            %get.RSS Get the value for property RSS
            rss = int16(obj.JavaMessage.getRSS);
        end
        
        function set.RSS(obj, rss)
            %set.RSS Set the value for property RSS
            validateattributes(rss, {'numeric'}, {'nonempty', 'scalar'}, 'DeviceRange', 'RSS');
            
            obj.JavaMessage.setRSS(rss);
        end
        
        function device = get.Device(obj)
            %get.Device Get the value for property Device
            device = char(obj.JavaMessage.getDevice);
        end
        
        function set.Device(obj, device)
            %set.Device Set the value for property Device
            validateattributes(device, {'char'}, {}, 'DeviceRange', 'Device');
            
            obj.JavaMessage.setDevice(device);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Timestamp = obj.Timestamp;
            cpObj.Distance = obj.Distance;
            cpObj.RSS = obj.RSS;
            cpObj.Device = obj.Device;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Timestamp = strObj.Timestamp;
            obj.Distance = strObj.Distance;
            obj.RSS = strObj.RSS;
            obj.Device = strObj.Device;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Timestamp = obj.Timestamp;
            strObj.Distance = obj.Distance;
            strObj.RSS = obj.RSS;
            strObj.Device = obj.Device;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.pozyx_ros_examples.DeviceRange.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.pozyx_ros_examples.DeviceRange;
            obj.reload(strObj);
        end
    end
end
